if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
  autoload -Uz compinit
  compinit
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# SSH and GPG
export "GPG_TTY=$(tty)"
export "SSH_AUTH_SOCK=${HOME}/.gnupg/S.gpg-agent.ssh"

source ~/.path

# Dev exports
export DEV=~/Documents/Developing

# Use 'exa' instead of 'ls'
alias ls='exa'
alias la='exa -la'
alias l='exa -l'
alias tree='exa -laT'

# Hash aliases
alias md5sum='gmd5sum'
alias sha1sum='gsha1sum'
alias sha256sum='gsha256sum'

# Amherst aliases
alias sshro='ssh ngrabermitchell22@romulus.amherst.edu'
alias sshre='ssh ngrabermitchell22@remus.amherst.edu'

alias py='python'

alias pg.start='pg_ctl -D /usr/local/var/postgres start > ~/pglog.log'
alias pg.stop='pg_ctl -D /usr/local/var/postgres stop'
alias pg.restart='pg_ctl -D /usr/local/var/postgres restart'

export GOPATH=$HOME/golang
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH="/usr/local/anaconda3/bin:$PATH"

. /Users/cgm616/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

if [ -d "$HOME/.pyenv" ]; then
  if [ -d "$HOME/.pyenv/bin" ]; then
    export PATH="$HOME/.pyenv/bin:$PATH"
  else
    export PATH="$HOME/.pyenv/shims:$PATH"
  fi
  if command -v pyenv >/dev/null 2>&1; then
    eval "$(pyenv init - --no-rehash)"
  fi
fi

export RUSTC_WRAPPER=sccache

export PATH=$PATH:/Applications/calibre.app/Contents/MacOS
